### ISSUE TITLE
how to convert bits to bytes with implicit padding of MSBs?

### ISSUE THREAD

**Issue by themighty1** [sinui0/itybity#13]
Hey, I was expecting that MSBs would be automatically zero-padded but it is not the case. This test fails:

```rust
 #[test]
    fn test() {
        assert_eq!(
            Vec::<u8>::from_msb0_iter("100000000".iter_bits()),
            vec![1, 0]
        );
    }
```

Is there a way to have itybity automatically zero-pad the MSBs to bring the total count of bits to the nearest multiple of 8?

**Comment by sinui0** [comment]
It is zero padded, I see this output from the test:

```
assertion `left == right` failed
  left: [128, 0]
 right: [1, 0]
```

`100000000` as MSB0 means the first byte is 128

**Comment by themighty1** [comment]
makes sense, thanks
