### ISSUE TITLE
`no_std` compile failure

### ISSUE THREAD

**Issue by arcnmx** [sinui0/itybity#9]
`itybity = { version = "0.2", default-features = false }` fails to compile:

> error[E0412]: cannot find type `Vec` in this scope
> itybity-0.2.0/src/traits.rs:231:32
> 231 |     fn to_bit_vec(&'a self) -> Vec<bool> {
> Vec not found in this scope
> error: could not compile `itybity` (lib) due to previous error

**Comment by sinui0** [comment]
Thanks, fixed in 0.2.1
